[package]

name = "piston"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>",
    "eddyb"
]

[lib]

name = "piston"
path = "./src/lib.rs"

[dependencies.vecmath]

git = "https://github.com/pistondevelopers/vecmath"

[dependencies.input]

git = "https://github.com/pistondevelopers/input"

[dependencies.event]

git = "https://github.com/bpicolo/event"

[dependencies.shader_version]

git = "https://github.com/pistondevelopers/shader_version"

[dependencies.cam]

git = "https://github.com/pistondevelopers/cam"

[dependencies.image]

git = "https://github.com/pistondevelopers/image"

[dependencies.graphics]

git = "https://github.com/pistondevelopers/graphics"

[dependencies.sprite]

git = "https://github.com/pistondevelopers/sprite"

[dependencies.noise-rs]

git = "https://github.com/bjz/noise-rs"

[dependencies.genmesh]

git = "https://github.com/csherratt/genmesh.git"

